[package]
name = "selene"
version = "0.2.0"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A blazing-fast modern Lua linter written in Rust"
categories = ["command-line-utilities"]
keywords = ["lua", "linter", "lua51"]
repository = "https://github.com/Kampfkarren/selene"
documentation = "https://kampfkarren.github.io/selene/"
edition = "2018"

[dependencies]
atty = "0.2"
codespan = "0.4"
codespan-reporting = "0.4"
full_moon = "0.4.0-rc.11"
lazy_static = "1.4"
glob = "0.3"
num_cpus = "1.10"
selene-lib = { path = "../selene-lib", version = "0.2.0" }
structopt = "0.3"
termcolor = "1.0"
threadpool = "1.7"
toml = "0.5"

[features]
roblox = ["selene-lib/roblox"]