name: Release selene
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  release:
    runs-on: ubuntu-latest
    needs: ['build_windows', 'build_mac', 'build_linux']
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - run: ls -R
      working-directory: artifacts
